-- ============================================================
-- CityServe — Supabase SQL Setup
-- Run this in Supabase SQL Editor (in order)
-- ============================================================


-- ============================================================
-- 0. EXTENSIONS
-- ============================================================

-- PostGIS for proper geo-radius queries (duplicate detection, etc.)
CREATE EXTENSION IF NOT EXISTS postgis;


-- ============================================================
-- 1. CITIES TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS cities (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL,           -- e.g. "new-delhi", "mumbai" (for URL use)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT cities_name_unique UNIQUE (name),
  CONSTRAINT cities_slug_unique UNIQUE (slug)
);

-- Seed some starter cities (adjust as needed)
INSERT INTO cities (name, slug) VALUES
  ('Delhi',     'delhi'),
  ('Mumbai',    'mumbai'),
  ('Bangalore', 'bangalore'),
  ('Hyderabad', 'hyderabad'),
  ('Chennai',   'chennai'),
  ('Kolkata',   'kolkata'),
  ('Pune',      'pune'),
  ('Jaipur',    'jaipur')
ON CONFLICT DO NOTHING;


-- ============================================================
-- 2. PROFILES TABLE
-- (Extends auth.users — created automatically via trigger)
-- ============================================================

CREATE TABLE IF NOT EXISTS profiles (
  id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name       TEXT NOT NULL,
  role            TEXT NOT NULL DEFAULT 'citizen'
                    CHECK (role IN ('citizen', 'admin')),
  city_id         UUID NOT NULL REFERENCES cities(id),

  -- Rate limiting: track when they last submitted an issue
  last_reported_at TIMESTAMPTZ,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- CONSTRAINT profiles_role_check CHECK (role IN ('citizen', 'admin'))
);

-- Index: admins/queries frequently filter by city
CREATE INDEX idx_profiles_city_id ON profiles(city_id);
CREATE INDEX idx_profiles_role     ON profiles(role);


-- ============================================================
-- 3. ISSUES TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS issues (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title         TEXT,                  -- auto-generated by AI (optional, not user-entered)
  description   TEXT NOT NULL,
  category      TEXT                   -- AI-assigned; NULL if Claude API was down
                  CHECK (category IN ('roads', 'garbage', 'water', 'lighting', 'encroachment', 'other', NULL)),
  severity      TEXT                   -- AI-estimated; NULL if Claude API was down
                  CHECK (severity IN ('low', 'medium', 'high', NULL)),
  status        TEXT NOT NULL DEFAULT 'reported'
                  CHECK (status IN ('reported', 'verified', 'in_progress', 'resolved')),

  city_id       UUID NOT NULL REFERENCES cities(id),
  reported_by   UUID NOT NULL REFERENCES auth.users(id),

  -- Geo: stored as PostGIS geography point for proper radius queries
  location      GEOGRAPHY(POINT, 4326),   -- primary geo column
  latitude      FLOAT8 NOT NULL,          -- kept for easy JS access
  longitude     FLOAT8 NOT NULL,

  image_url     TEXT,                  -- Supabase Storage URL

  upvotes_count INT4 NOT NULL DEFAULT 0,

  -- Soft delete — never hard-delete civic data
  deleted_at    TIMESTAMPTZ,

  resolved_at   TIMESTAMPTZ,           -- auto-set when status → resolved
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes — these are the queries that will run constantly
CREATE INDEX idx_issues_city_id        ON issues(city_id);
CREATE INDEX idx_issues_status         ON issues(status);
CREATE INDEX idx_issues_category       ON issues(category);
CREATE INDEX idx_issues_reported_by    ON issues(reported_by);
CREATE INDEX idx_issues_city_status    ON issues(city_id, status);       -- admin dashboard
CREATE INDEX idx_issues_city_category  ON issues(city_id, category);     -- map filters
CREATE INDEX idx_issues_deleted_at     ON issues(deleted_at);            -- soft delete filter
CREATE INDEX idx_issues_location       ON issues USING GIST(location);   -- geo radius queries
CREATE INDEX idx_issues_created_at     ON issues(created_at DESC);       -- sorting


-- ============================================================
-- 4. UPVOTES TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS upvotes (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  issue_id    UUID NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Prevents duplicate upvotes at the DB level (not just app level)
  CONSTRAINT upvotes_unique_per_user UNIQUE (user_id, issue_id)
);

CREATE INDEX idx_upvotes_issue_id ON upvotes(issue_id);
CREATE INDEX idx_upvotes_user_id  ON upvotes(user_id);


-- ============================================================
-- 5. TRIGGERS
-- ============================================================

-- 5.1 Auto-create profile when a new user registers
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, city_id)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    COALESCE(NEW.raw_user_meta_data->>'role', 'citizen'),
    (NEW.raw_user_meta_data->>'city_id')::UUID
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();


-- 5.2 Auto-set resolved_at when status changes to 'resolved'
CREATE OR REPLACE FUNCTION handle_issue_resolved()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'resolved' AND OLD.status != 'resolved' THEN
    NEW.resolved_at = NOW();
  END IF;

  -- Also clear resolved_at if status is reverted (edge case)
  IF NEW.status != 'resolved' AND OLD.status = 'resolved' THEN
    NEW.resolved_at = NULL;
  END IF;

  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_issue_status_change
  BEFORE UPDATE ON issues
  FOR EACH ROW EXECUTE FUNCTION handle_issue_resolved();


-- 5.3 Auto-update updated_at on any issues row change
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_issues_updated
  BEFORE UPDATE ON issues
  FOR EACH ROW EXECUTE FUNCTION handle_updated_at();


-- 5.4 Sync upvotes_count when upvote is added
CREATE OR REPLACE FUNCTION handle_upvote_insert()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE issues
  SET upvotes_count = upvotes_count + 1
  WHERE id = NEW.issue_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_upvote_added
  AFTER INSERT ON upvotes
  FOR EACH ROW EXECUTE FUNCTION handle_upvote_insert();


-- 5.5 Sync upvotes_count when upvote is removed
CREATE OR REPLACE FUNCTION handle_upvote_delete()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE issues
  SET upvotes_count = GREATEST(upvotes_count - 1, 0)   -- never goes below 0
  WHERE id = OLD.issue_id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_upvote_removed
  AFTER DELETE ON upvotes
  FOR EACH ROW EXECUTE FUNCTION handle_upvote_delete();


-- 5.6 Auto-set location geography point from lat/lng on insert/update
CREATE OR REPLACE FUNCTION handle_issue_location()
RETURNS TRIGGER AS $$
BEGIN
  NEW.location = ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326)::GEOGRAPHY;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_issue_location_set
  BEFORE INSERT OR UPDATE OF latitude, longitude ON issues
  FOR EACH ROW EXECUTE FUNCTION handle_issue_location();


-- ============================================================
-- 6. HELPER FUNCTION — nearby issues (for duplicate detection)
-- Usage: SELECT * FROM get_nearby_issues('uuid', 28.6139, 77.2090, 500, 'roads');
-- ============================================================

CREATE OR REPLACE FUNCTION get_nearby_issues(
  p_city_id    UUID,
  p_latitude   FLOAT8,
  p_longitude  FLOAT8,
  p_radius_m   FLOAT8 DEFAULT 500,
  p_category   TEXT   DEFAULT NULL
)
RETURNS SETOF issues AS $$
BEGIN
  RETURN QUERY
  SELECT i.*
  FROM issues i
  WHERE
    i.city_id = p_city_id
    AND i.deleted_at IS NULL
    AND i.status != 'resolved'
    AND ST_DWithin(
      i.location,
      ST_SetSRID(ST_MakePoint(p_longitude, p_latitude), 4326)::GEOGRAPHY,
      p_radius_m
    )
    AND (p_category IS NULL OR i.category = p_category);
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 7. HELPER FUNCTION — recalculate upvotes_count (reconciliation)
-- Run periodically or after manual DB edits
-- ============================================================

CREATE OR REPLACE FUNCTION recalculate_upvotes()
RETURNS VOID AS $$
BEGIN
  UPDATE issues i
  SET upvotes_count = (
    SELECT COUNT(*) FROM upvotes u WHERE u.issue_id = i.id
  );
END;
$$ LANGUAGE plpgsql;
